### PR TITLE
fix(meta): corrected common library urls [ci-skip]

### PR DESCRIPTION
**Pull request by acjohnson**

### CODE REVIEW

**Comment by onedr0p** [comment]
these also need to be update in out helm-docs templates

https://github.com/k8s-at-home/charts/tree/master/templates/chart

thanks :)

**Comment by acjohnson** [comment]
ah yeah missed the templates. should be good now. I was gonna say we don't want to bump all the chart versions for doc fixes :smile:

**Comment by onedr0p** [comment]
Yup! It's fine, but there's currently a manual task of fix the CI for future PRs. I'll go ahead and merge it, thanks for fixing this up. We overlooked them for sure!

**Review by onedr0p — APPROVED** [review]

**Comment by onedr0p** [comment]
@allcontributors add @acjohnson for code

**Pull request merged**
