### PR TITLE
[focalboard] Update chart to include enableServiceLinks: true

### LINKED ISSUE #1303: [focalboard] Chart's default vaules causes pod to CrashBackOffLoop
# Details

**Helm chart name and version:**
focalboard v4.1.0

**Container name and tag:**
mattermost/focalboard:0.11.0

**What steps did you take and what happened:**
Installed the helm chart to my cluster via Kustomization HelmRelease and the Pod goes into a CrashBackOffLoop

**Relevant Helm values:**
Changed no default values but the container image tag to 0.11.0 (most recent), and setup ingress/persistent storage

```
image:
  # -- image repository
  repository: mattermost/focalboard
  # -- image pull policy
  pullPolicy: IfNotPresent
  # -- image tag
  tag: 0.11.0

# -- environment variables.
# @default -- See below
env: {}

# See the Administrator's Guide for config reference: https://www.focalboard.com/guide/admin/
config: |
  {
    "serverRoot": "http://localhost:8000",
    "port": 8000,
    "dbtype": "sqlite3",
    "dbconfig": "/data/focalboard.db",
    "postgres_dbconfig": "dbname=focalboard sslmode=disable",
    "useSSL": false,
    "webpath": "./pack",
    "filespath": "/data/files",
    "telemetry": true,
    "session_expire_time": 2592000,
    "session_refresh_time": 18000,
    "localOnly": false,
    "enableLocalMode": true,
    "localModeSocketLocation": "/var/tmp/focalboard_local.socket"
  }

ingress:
  main:
    enabled: true
    ingressClassName: "traefik"
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-production"
      hajimari.io/enable: "true"
      hajimari.io/icon: "notebook-outline"
      traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      traefik.ingress.kubernetes.io/router.middlewares: "networking-basic-auth@kubernetescrd"
    hosts:
      - host: "focalboard.${SECRET_DOMAIN}"
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - "focalboard.${SECRET_DOMAIN}"
        secretName: focalboard-tls

persistence:
  data:
    enabled: true
    existingClaim: focalboard-data-v1
```

**What did you expect to happen:**
I expected the chart to install and the container to come up

**Anything else you would like to add:**
The Pod goes into a crashBackOffLoop with the following error from the pod logs

```
# kubectl logs -f focalboard-d75b98894-bpht6 -n productivity
2021/12/11 14:13:20 Unable to read the config file: 1 error(s) decoding:

* cannot parse 'port' as int: strconv.ParseInt: parsing "tcp://10.43.219.133:8000": invalid syntax
```

**Additional Information:**
It appears based on the error that something is overwriting the config "port' with tcp://10.43.219.133:8000 when it is set to 8000 in the helm-release

### PR DESCRIPTION
**Pull request by PrymalInstynct**
**Description of the change**
Added `enableServiceLinks: false` to values.yaml which is missing causes the Pod to CrashBackOffLoop

**Benefits**
The Chart works again with its default values

**Possible drawbacks**
None

**Applicable issues**

- fixes #1303 

**Additional information**

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [x] Variables are documented in the README.md (this can be done with using our helm-docs wrapper `./hack/gen-helm-docs.sh table <chart>`)

### CODE REVIEW

**Comment by bjw-s** [comment]
This seems to only become an issue when you name your helm release `focalboard`. I'm not sure if we want to disable the servicelinks by default, since people might rely on them somehow. It might be better to add a note to the configuration docs about it. @onedr0p what do you think?

**Comment by onedr0p** [comment]
Aye, having a clear concise description would make more since.

**Comment by PrymalInstynct** [comment]
How about the change I just commited to make people aware of the need based on situation?

**Comment by bjw-s** [comment]
I personally think the documentation for this should go in to the `README_CONFIG.md.gotmpl` file (replacing the `N/A`) instead of in the values.yaml file.

Perhaps something like:

> By default Kubernetes will create several environment variables called service links (see [here](https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/#accessing-the-service) for more information). 
>
> Focalboard can be configured with environment variables, so when you deploy this Helm release with a name of `focalboard` these service links will conflict with the application.
>
> In order to prevent this, you can disable the creation of these service links by setting `enableServiceLinks: false` in your `values.yaml.

**Comment by bjw-s** [comment]
Implemented by #1324

**Pull request closed without merging**
