### PR TITLE
[adguard-home] Add pullPolicy for configmap init

### PR DESCRIPTION
**Pull request by ElGranLoky**
If adguard is not working no dns, best use IfNotPresent for configmap init.

### CODE REVIEW

**Comment by onedr0p** [comment]
I'm alright with this change but please bump the chart version and re-run helm-docs. Thanks!

**Review by onedr0p — APPROVED** [review]

**Comment by onedr0p** [comment]
@ElGranLoky I just wanted to say your k8s nodes should not be relying on Adguard for DNS. Therefore you should not lose DNS during a update.

**Comment by ElGranLoky** [comment]
Thanks @onedr0p.

I fix it in my deployment. I added a public dns in secundary nameserver in the nodes.

I was also thinking about the rate limit from pull request in docker hub.

**Comment by onedr0p** [comment]
@ElGranLoky adding a secondary dns that's public doesn't matter. When DNS requests are looked up it randomly chooses one and if it fails it doesn't fall back to the secondary DNS. It's wise to only put one DNS provider. See some of my guidelines here. https://onedr0p.github.io/home-cluster/installation/guidelines/

Also, you dockerhub rate limit is another issue but we could try and replace BusyBox with a image not hosted there.

**Comment by ElGranLoky** [comment]
@onedr0p Thanks for the guideline

**Pull request merged**
