### PR TITLE
[blocky] use container image direct from the application developer

### PR DESCRIPTION
**Pull request by haraldkoch**
It's possible that when this chart was first built, container images (or multi-arch images) were not available - but they are now. See https://github.com/0xERR0R/blocky/pkgs/container/blocky for images that include amd64, arm64, arm/v6, and arm/v7.

**Description of the change**

This change changes the blocky helm chart to use container images built by the app maintainer.

**Benefits**

Container images direct from the source are published sooner and theoretically more reliable.

**Possible drawbacks**

unknown?

**Applicable issues**

- fixes #

**Additional information**

**Checklist** 
- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [ ] Variables are documented in the README.md (this can be done with using our helm-docs wrapper `./hack/gen-helm-docs.sh stable <chart>`)

### CODE REVIEW

**Comment by haraldkoch** [comment]
I updated the Chart.yaml version after I first created the pull request. Since the two container images should be effectively identical, I didn't think a semver update beyond "patch" was required, but I can change that.

It seems changelog entries are only added for major version changes, and this is a minor update?

**Comment by bjw-s** [comment]
> I updated the Chart.yaml version after I first created the pull request. Since the two container images should be effectively identical, I didn't think a semver update beyond "patch" was required, but I can change that.

Updating the patch level is fine 👍

As for the changelog, you will need to modify the `README_CHANGELOG.md.gotmpl` file, since the README.md file is automatically generated from those templates and your current changes would be overwritten.

> It seems changelog entries are only added for major version changes, and this is a patch update?

We normally add change notes to all releases except for the ones that are because of minor/patch version updates of the underlying common library (the tool we use for the updates has no idea about our changelogs, and it would be a lot of manual work to update all the chart docs).

**Comment by haraldkoch** [comment]
Got it. None of the charts I use have had minor updates that I've seen, I incorrectly assumed this was a pattern.

Does that look better?

**Review by onedr0p — APPROVED** [review]

**Comment by haraldkoch** [comment]
Two questions:

1) "This branch is out-of-date" - rebase from master, or just merge the changes?
2) should I squash the four commits into one (and force-push the branch)? Or just leave it alone?

**Comment by onedr0p** [comment]
You are all good, unless there were conflicts we just squash and merge (even if the branch is technically out of date)

**Pull request merged**
