### PR TITLE
[teslamate] Can't login with old docker image

### PR DESCRIPTION
**Pull request by EasternPA**
I fought with failed logins (Error: Unknown) for the past two days until I finally forced it to use the latest Docker image.

**Description of the change**

**Benefits**

**Possible drawbacks**

**Applicable issues**

- fixes #

**Additional information**

**Checklist** 
- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [ ] (optional) Chart is using our [common](https://github.com/k8s-at-home/charts/tree/master/charts/common) library as a dependency.
- [ ] (optional) Variables are documented in the README.md

### CODE REVIEW

**Comment by billimek** [comment]
Thanks for this PR @EasternPA!  Can you please do a couple more things from the checklist?

* Bump the chart version in `Chart.yaml`
* Modify the title of the PR to be prefixed with `[teslamate]`

**Comment by EasternPA** [comment]
> Thanks for this PR @EasternPA! Can you please do a couple more things from the checklist?
> 
> * Bump the chart version in `Chart.yaml`
> * Modify the title of the PR to be prefixed with `[teslamate]`

Sorry Jeff, I don't know how to add additional files to an existing PR. I ended up creating a second one that only updates Chart.yaml as requested.

**Comment by EasternPA** [comment]
> Thanks for this PR @EasternPA! Can you please do a couple more things from the checklist?
> 
> * Bump the chart version in `Chart.yaml`
> * Modify the title of the PR to be prefixed with `[teslamate]`

I deleted this PR and tried to create another one that changes both files, but GH only wants to update one file at a time. Maybe you can offer a tip. Until then, I just closed it.

**Comment by onedr0p** [comment]
Don't use the web-ui,  fork our this repo and use the git CLI to make changes.

**Pull request closed without merging**
