### PR TITLE
[paperless] chore: switch to paperless-ngx project

### PR DESCRIPTION
**Pull request by morremeyer**
**Description of the change**

This switches to the community fork of paperless-ng. The tracking ticket in paperless-ngx is https://github.com/paperless-ngx/paperless-ngx/issues/68.

Please see the following references for the community discussion of the decision to fork:

* https://github.com/jonaswinkler/paperless-ng/issues/1599
* https://github.com/jonaswinkler/paperless-ng/issues/1632.

**Benefits**

Switch to the community maintained **paperless-ngx** fork.

**Possible drawbacks**

None that I am aware of.

**Additional information**

This is a non-breaking change for the paperless application itself, but as it changes the upstream, I've opted to bump the major version.

**Checklist** 
- [x] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Chart `artifacthub.io/changes` changelog annotation has been updated in `Chart.yaml`. See [Artifact Hub documentation](https://artifacthub.io/docs/topics/annotations/helm/#supported-annotations) for more info.
- [x] Variables have been documented in the `values.yaml` file.

### CODE REVIEW

**Comment by morremeyer** [comment]
Can someone please advise me how to correctly update the README? I can't find documentation for it, although it suspiciously looks like helm-docs.

**Comment by bjw-s** [comment]
> Can someone please advise me how to correctly update the README? I can't find documentation for it, although it suspiciously looks like helm-docs. 

No need to manually update the README, we auto-generate that upon merging the PR. Any manual modifications will be lost then.

I will take a look at the PR later tonight 😃

**Comment by morremeyer** [comment]
@bjw-s that's good to know, thanks! How can I take care of updating the `Source Code` section then? I didn't find it anywhere else and updated it directly in the README.md for that reason (https://github.com/k8s-at-home/charts/pull/1436/files#diff-2e548bd16ddaf26ec88fbd01ce605997e61c43301e73c5a723aaf90a21908156R11)

**Comment by angelnu** [comment]
@morremeyer - that is in at https://github.com/k8s-at-home/charts/blob/ab59fc8c6e58d0146c052086a07438dad5fb6389/charts/stable/paperless/Chart.yaml#L12

As user of paperless and contributor to the k8s-at-home I am really glad to see the project moves on. So no reason for not switching the chart to the new community fork.

**Review by bjw-s — CHANGES_REQUESTED** [review]
The changes look good, thanks for making this PR and moving us to the new fork!
Just a tiny change requested before I merge it.

**Comment by morremeyer** [comment]
@bjw-s Thanks for the review. I overlooked that you added it as a suggestion, so I updated it locally.

**Review by bjw-s — APPROVED** [review]

**Pull request merged**
