### PR TITLE
[Mosquitto] Update Mosquitto to support configurable ports

### PR DESCRIPTION
**Pull request by brainstain**
**Description of the change**

Updated the service to have configurable ports for users that wish to run on non-standard. 

**Benefits**

Users can configure the ports that they want the service to expose

**Possible drawbacks**

**Applicable issues**

**Additional information**
Tested on microk8s 

**Checklist** 
- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Title of the PR starts with chart name (e.g. `[home-assistant]`)

### CODE REVIEW

**Comment by onedr0p** [comment]
This might be confusing for people if you don't show how to change the non standard port of the application, is it a cli arg, environment variable?

**Comment by brainstain** [comment]
@onedr0p It is configurable via the values.yaml file and the defaults are in place.  This change would not impact anyone utilizing the chart.  https://github.com/k8s-at-home/charts/pull/475/files#diff-59790794f32c9f4d795399384f2551f17017e20fe5fd422b3c2cea5506f5eb1fR37-R38

Did I misunderstand your suggestion?

**Comment by onedr0p** [comment]
The application by default uses port 1883 and 9001. If someone wanted to use different ports the application won't start because the ports in the container would still be 1883 and 9001.

**Comment by bjw-s** [comment]
> The application by default uses port 1883 and 9001. If someone wanted to use different ports the application won't start because the ports in the container that the application is using would still be 1883 and 9001.

Yep, also, the container ports are also still listening on 1883 and 9001: https://github.com/brainstain/charts/blob/5eecbb6f14fcc5625defa4d1dae1d59d2c2dd0b7/charts/mosquitto/templates/statefullset.yaml#L52

**Comment by brainstain** [comment]
Odd, this works on my deployment.  My understanding is since it is a named port, k8s will bind the exposed service port to  the one that is exposed via the container.  I'll do more testing to verify.

**Comment by brainstain** [comment]
Container ports are informational only, per the k8s docs https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/: 

List of ports to expose from the container. Exposing a port here gives the system additional information about the network connections a container uses, but is primarily informational. Not specifying a port here DOES NOT prevent that port from being exposed. Any port which is listening on the default "0.0.0.0" address inside a container will be accessible from the network. Cannot be updated.
--
I can add a target port to the service.

**Comment by bjw-s** [comment]
Even if it is only informative and doesn't affect the operation of the deployment, it would still be nice if the information was correct. Personally I would like to see that the service ports are 'dynamic' in the statefulset too.

**Comment by brainstain** [comment]
Okay, I did more research into this, and the implementation is correct.  If you look at the service, it includes the targetport as a named entity: default & websocket respectively.  https://github.com/brainstain/charts/blob/5eecbb6f14fcc5625defa4d1dae1d59d2c2dd0b7/charts/mosquitto/templates/service.yaml#L21

These are named in the statefulset: https://github.com/brainstain/charts/blob/5eecbb6f14fcc5625defa4d1dae1d59d2c2dd0b7/charts/mosquitto/templates/statefullset.yaml#L51

What this does is map the port defined in the service to the port listened to by the container.  I don't want to update the listed container port because that would be misleading if someone wanted to use a type of NodePort to do port forwarding

**Comment by brainstain** [comment]
FWIW, I tested this on multiple different types of ports and is working as expected.

**Comment by onedr0p** [comment]
Ok that makes sense! Thanks for the follow up, we can get this merged :)

**Pull request merged**
