### PR TITLE
[Mosquitto] upgrade to 2.0.4

### PR DESCRIPTION
**Pull request by lazyoldbear**
Upgraded from 1.6.x to 2.x, with minimal changes to the default config to allow it work out of the box in insecure way. 

Signed-off-by: Ingvarr Zhmakin

### CODE REVIEW

**Comment by lazyoldbear** [comment]
Apologies, broke persistence. Corrected just now.

**Comment by onedr0p** [comment]
This looks like maybe a potential breaking change, should the chart version be bumped to `1.0.0`?

**Comment by lazyoldbear** [comment]
Well, based on what I see in Mosquitto changes, they are more security cleanup. And the default config is "just work", with an advantage of more relevant starting point in configuration. 
Besides, 1.x was in 0.x of the chart. The changes do not really look that dramatic. 
Regardless, I am happy to live with any version policy.

**Comment by onedr0p** [comment]
Looking into it more, you are right, we don't need a 1.0.0 release. Let's merge it as is :)

**Review by onedr0p — APPROVED** [review]

**Pull request merged**
