### PR TITLE
Add improvements to the home-assistant chart

### PR DESCRIPTION
**Pull request by mkenne11**
**Description of the change**

Added improvements to the home-assistant chart including:
- Instructions for installing codeserver to the README file
- Ingress configuration to the values.yaml file

**Benefits**

The changes for configuring codeserver (as a configuration file editor) and an ingress (for the home-assistant web application) are common settings that a significant number of users will want to implement.

**Possible drawbacks**

A potential drawback is codeserver requires a significant amount of cpu and memory resources that users on low power devices (such as a rpi) may not always have.

**Applicable issues**

This is change is an enhancement and does not fix any issues. No potential issues have been identified.

### CODE REVIEW

**Comment by mkenne11** [comment]
I got an error in the repository CI/CD test - it indicates I'm using an old chart version, when the version of the chart I'm using is current. Does this message relate to a different issue?

See linter error message below:
```
Old chart version: 5.2.2
Error: Error linting charts: Error processing charts
New chart version: 5.2.2
------------------------------------------------------------------------------------------------------------------------
 ✖︎ home-assistant => (version: "5.2.2", path: "charts/home-assistant") > Chart version not ok. Needs a version bump!
------------------------------------------------------------------------------------------------------------------------
Error linting charts: Error processing charts
Error: Process completed with exit code 1.
```

**Comment by bjw-s** [comment]
Thanks for the PR! I'm having some doubts about this one, as it is decentralizing default settings and documentation that are (or could better go) in the central `common` library chart. This will potentially increase maintenance cost when we make changes to that library.

**Comment by onedr0p** [comment]
I agree, this can be said about all the charts, not just home assistant. We need to work on a centralized wiki for charts using the common library

**Comment by onedr0p** [comment]
Closing in favor of this issue. We hear you these things need to be documented, but putting them in each chart may not be the way forward.

https://github.com/k8s-at-home/charts/issues/461

**Comment by mkenne11** [comment]
No problems @bjw-s and @onedr0p that makes sense. My suggested changes would apply to quite a few charts so it makes sense to document them in a common wiki area.
Btw I think I'm reasonably familiar with helm charts, and still had to do quite a bit of digging to work out how to add codeserver to home-assistant. Common wiki content would help, especially for those who aren't that familiar with charts.

**Pull request closed without merging**
