### PR TITLE
[pod-gateway] Fix bug with duplicate strategy definitions in webhook-deployment.yaml

### PR DESCRIPTION
**Pull request by jmmaloney4**
**Description of the change**

Remove one of the `strategy:` definitions in webhook-deployment.yaml. This was causing validation errors when installing.

**Benefits**

Chart should pass helm/kubectl validator now.

**Possible drawbacks**

**Applicable issues**

- fixes #

**Additional information**

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [x] Variables are documented in the README.md (this can be done with using our helm-docs wrapper `./hack/gen-helm-docs.sh stable <chart>`)

### CODE REVIEW

**Comment by bjw-s** [comment]
I've asked @angelnu to chime in on which one of the two `strategy` blocks he wants to keep around :)

**Comment by jmmaloney4** [comment]
Ok. The one I deleted seems totally redundant. The one being kept is:
```
{{- with .Values.webhook.strategy }}
strategy:
  {{- toYaml . | nindent 4 }}
{{- end }}
```
And the one I removed is:
```
strategy:
  type: {{ .Values.webhook.strategy.type }}
```
So there should be no change to the `values.yaml`, just that fields other than `type` will get filled in.

**Review by angelnu — APPROVED** [review]
Fix is good - the one at the bottom only considers the type while the one on the top takes any content under the webhook strategy.

Thanks @jmmaloney4

**Review by bjw-s — APPROVED** [review]

**Comment by bjw-s** [comment]
@all-contributors please add @jmmaloney4 for code

**Pull request merged**
