### PR TITLE
[xbvr] Add new chart

### PR DESCRIPTION
**Pull request by CoolMintChocolate**
**Description of the change**

Add chart for XBVR - a tool for managing your VR porn collection.

**Benefits**

New chart.

**Possible drawbacks**

N/A

**Applicable issues**

N/A

**Additional information**

**Checklist** 
- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [X] Variables are documented in the README.md (this can be done with using our helm-docs wrapper `./hack/gen-helm-docs.sh stable <chart>`)

### CODE REVIEW

**Comment by onedr0p** [comment]
Thanks @CoolMintChocolate ! Please move this into the stable folder and make the chart version 1.0.0.

**Comment by CoolMintChocolate** [comment]
@onedr0p will do! Out of curiosity what's the `incubator` folder used for? I'd have thought that new charts must go through that first before getting promoted to `stable`.

**Comment by onedr0p** [comment]
It was mainly an idea of helm charts that would require a lot of custom configuration that don't play nice with the our common chart. I know we haven't specified this anywhere but the majority of helm charts can go directly to stable.

**Comment by CoolMintChocolate** [comment]
I've made the requested changes to move the chart to `stable` folder and made the version `1.0.0`.

**Review by onedr0p — APPROVED** [review]

**Comment by onedr0p** [comment]
Sorry it took so long, thanks again!

**Comment by onedr0p** [comment]
@all-contributors please add @CoolMintChocolate for code

**Pull request merged**
