### PR TITLE
[home-assistant] Update default image

### PR DESCRIPTION
**Pull request by bjw-s**
**Description of the change**

**Benefits**

**Possible drawbacks**

**Applicable issues**

- fixes #

**Additional information**

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [x] Chart is using our [common](https://github.com/k8s-at-home/charts/tree/master/charts/common) library as a dependency.
- [ ] (optional) Variables are documented in the README.md

### CODE REVIEW

**Review by onedr0p — APPROVED** [review]

**Comment by k4pu77** [comment]
May I ask why the version 5.4.3 is not available at https://artifacthub.io/packages/helm/k8s-at-home/home-assistant?

**Comment by onedr0p** [comment]
May some issue with the release, we will try it again

**Comment by onedr0p** [comment]
5.4.4 is up :)

**Comment by k4pu77** [comment]
@onedr0p Thank you for your effort!

**Pull request merged**
