### PR TITLE
[pod-gateway] Fix for allowing custom namespace selectors without dict merges

### PR DESCRIPTION
**Pull request by toboshii**
**Description of the change**

Currently `namespaceSelector` is defined as a dict to match k8s format, however this causes an issue if one wants to set a custom namespace label as Helm merges the values ending up with multiple labels.

This change allows setting custom labels that won't be merged, while still allowing complex custom selectors if needed.

**Benefits**

Fixes implementation to work as originally intended.

**Possible drawbacks**

Breaking change for users that have already attempted to use custom `namespaceSelector`s (probably just me :) )

**Applicable issues**

**Additional information**

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [x] Variables are documented in the README.md (this can be done with using our helm-docs wrapper `./hack/gen-helm-docs.sh stable <chart>`)

### CODE REVIEW

**Review by angelnu — APPROVED** [review]
Discussed with @toboshii in Discord - Thanks for the PR!

**Comment by angelnu** [comment]
@bjw-s - btw, it looks like the title check is still not happy with dashes.

**Comment by bjw-s** [comment]
> @bjw-s - btw, it looks like the title check is still not happy with dashes.

It actually is :) the label was removed by the bot after the space was removed from the chart name. 
Thanks for the approval on the PR, will merge it in a bit.

**Review by bjw-s — APPROVED** [review]

**Comment by angelnu** [comment]
ups, sorry - I merged it already since you and I had approved @bjw-s Was there any other dep you were waiting for?

**Comment by bjw-s** [comment]
No, I was just waiting for the branch update to finish and then got called away for a bit :) Thanks for the assist!

**Pull request merged**
