### PR TITLE
[intel-gpu-plugin] Migrate to common library

### PR DESCRIPTION
**Pull request by nicholaswilde**
Signed-off-by: Nicholas Wilde <ncwilde43@gmail.com>

**Description of the change**

Migrated to common library.

**Benefits**

**Possible drawbacks**

**Applicable issues**

- fixes #

**Additional information**

**Checklist** 
- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [X] Variables are documented in the README.md (this can be done with using our helm-docs wrapper `./hack/gen-helm-docs.sh stable <chart>`)

### CODE REVIEW

**Review by bjw-s — APPROVED** [review]
LGTM

**Comment by Diaoul** [comment]
> Migrate to the common library, a lot of configuration has changed.

That's not very specific.

**Comment by onedr0p** [comment]
It's hard to be specific. It's literally like a new chart.

**Comment by Diaoul** [comment]
I know, but I think a few highlights on the key changes (that are used for this chart) would be great, for the most common use case.

For the future reader (if any), I have a standard configuration and I was able to switch to this chart without changing anything but I think if you used anything specific you need to make some changes, like with `sharedDeviceNumber`.

**Pull request merged**
