### PR TITLE
[deconz] Migrate to common (reason: Fix labels that prevent upgrading)

### PR DESCRIPTION
**Pull request by CuBiC3D**
**Description of the change**

Removed version labels (change every release) from `spec.VolumeClaimTemplate.metadata.labels` of the `StatefulSet`. Those template fields are immutable on `StatefulSets` and do prevent any upgrades to the chart by Helm.

```
Error: UPGRADE FAILED: cannot patch "deconz" with kind StatefulSet: StatefulSet.apps "deconz" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
```
See https://github.com/helm/charts/issues/7803

Also adds back the `timeoutSeconds: 10` value for readiness probe - the documenting comment was there but the value somehow disappeared. Empty fields that will be populated with standard values by kubernetes API can lead problems with tools like ArgoCD that check for resource diversion.

**Benefits**
Upgrading possible ;)

**Possible drawbacks**
Breaking change will require to delete the old `StatefulSet` or uninstall release. But upgrades currently not work anyways.

**Applicable issues**

none

**Additional information**

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [ ] (optional) Chart is using our [common](https://github.com/k8s-at-home/charts/tree/master/charts/common) library as a dependency.
- [x] (optional) Variables are documented in the README.md

### CODE REVIEW

**Comment by onedr0p** [comment]
I wonder if it's worth coverting this to use the common library. 🤔

**Comment by CuBiC3D** [comment]
> I wonder if it's worth coverting this to use the common library.

Already thought about that and it probably is, but should we do that prior to fix or fix and convert after?

**Comment by bjw-s** [comment]
I would prefer doing it now... That way we only have one breaking change, and the labels problem will be fixed "automatically" as well.

**Comment by CuBiC3D** [comment]
Then let's close this and I'll move it over to common today/weekend ;)

**Comment by CuBiC3D** [comment]
Actually we can keep this branch, I'll change it to draft for now

**Comment by CuBiC3D** [comment]
Migrated to common chart and documented necessary configuration with comments in `values.yaml`. Small migration info is in readme. Upgraded on real cluster+device with `helm update`, runs fine. Let me know if there's something to improve :)

**Comment by CuBiC3D** [comment]
I'll take a look at CI later ;)

**Review by onedr0p — APPROVED** [review]

**Pull request merged**
