### PR TITLE
[frigate] Update frigate to 8.0.0

### PR DESCRIPTION
**Pull request by bjw-s**
**Description of the change**

- Update Frigate image tag to 0.10.0
- Replace `config` key with common library `configmap` support

**Benefits**

**Possible drawbacks**

**Applicable issues**

- fixes #

**Additional information**

**Checklist** 
- [x] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Chart `artifacthub.io/changes` changelog annotation has been updated in `Chart.yaml`. See [Artifact Hub documentation](https://artifacthub.io/docs/topics/annotations/helm/#supported-annotations) for more info.
- [x] Variables have been documented in the `values.yaml` file.

### CODE REVIEW

**Review by onedr0p — APPROVED** [review]

**Comment by bjw-s** [comment]
It was a breaking release, and there was mention of both breakage due to the Frigate update _and_ the fact that there is now a different way to specify the configuration. 

I am not sure what more we should have put in the changelog without it becoming super verbose.

**Comment by brujoand** [comment]
Just adding the description of this PR would have been more than enough. 

```
- Update Frigate image tag to 0.10.0
- Replace config key with common library configmap support
```

I’m not seeing any text on the chart readme under the update section. Am I looking in the wrong place?

**Comment by bjw-s** [comment]
Ooh, you are right... something seems to be acting up with our README generator 😮It's supposed to be generated from the Chart.yaml annotations.
I will look in to that. Thanks for reporting this!

**Comment by bjw-s** [comment]
README has been fixed. It was due to how we mentioned the breaking changes. Apparently our script didn't like that line being unquoted. Thanks again for pointing me at it.

**Comment by brujoand** [comment]
Great, thanks! 👍

**Pull request merged**
