### PR TITLE
[dendrite] Add dendrite polylith mode

### LINKED ISSUE #1367: Supprt Dendrite in polylith mode
# Details

**Helm chart name:** Dendrite

**Describe the solution you'd like:** A dendrite deployment using k8s-at-home library charts

There has been discussions among @S7evink, and @Jonnobrow I about support dendrite in a polylith deployment model. This issue should track it's progress. The current contigency plan is to add each component as a dependency to the [current dendrite](https://github.com/k8s-at-home/charts/tree/master/charts/incubator/dendrite) deployment.

Progress is being made [here](https://github.com/anthr76/charts/commits/feat-poly) and if you'd like to be added as a contributor to help complete the dendrite polylith chart please contact me via discord or matrix via:
anthr76#1885
anthr76:mozilla.org

A rough outline of what needs to happen

- [ ] Create simple microservice deployments exposing only a service and container deployment sepc for [all of the components of dendrite](https://github.com/matrix-org/dendrite/blob/master/docs/INSTALL.md#starting-a-polylith-deployment)
- [ ] Add a switch in the values of the existing dendrite deployment to enable polylith or monolith
- [ ] Suppport private key generate and helm dependencies for postgress and nats

This chart release should be blocked until a NATs release is cut from dendrite and we should template the config around dendrite's mono config version 2

**Anything else you would like to add:**

**Additional Information:**

A chat log about efforts.

> anthr76
> Hi there jonnobrow. S7evink and I were interested in coming together and adding polylith support to the Kubernetes at home dendrite chart. Would this something you're interested in?
> jonnobrow
> Hi, that sounds great. I'm more than happy for you both to take the lead on it and I'll help out if needed 🙂
> s7evink
> I'll need to understand the layout of k8s-at-home first, it is slightly confusing :D
> jonnobrow
> Yeah definitely :) its worth checking out the docs on creating a new chart. They run you through the tools you'll need and introduce using the library chart templates.
> 
> For implementing polylith we will almost certainly need some advanced logic as there will be multiple deployments which is not the default for most things.
> 
> If you have any questions about getting started give me a shout and I'm happy to help :)
> 
> Also perhaps look at the library chart to see what is available in the way of templates so you don't do any work thats already been done for you :)
> Finally, for kafka, I think we can include it as a dependency like postgres or the common chart since there is a chart maintained by bitnami
> s7evink
> Will have a look, thanks :)
> I don't think we need Kafka, the next release will require NATS instead of Kafka. :)
> anthr76
> I wonder if it's possible if we can create a branch off a forked repo and all make pushes to it. That should be possible?
> Indeed I just invited both of you to my forked repo. Feel free to make pushes on the feat-poly branch
> anthr76
> image.png
> This is a note from onedr0p a admin for KaH 
> jonnobrow
> Interesting, I supposed we could keep each components chart fairly simple (especially with config) and do any clever config logic in the parent polylith chart? Otherwise I worry we would be duplicating a lot of stuff
> Another approach might be to have a single component chart which we can parameterize and include as a dependency multiple times with dependency aliasing: https://helm.sh/docs/topics/charts/#alias-field-in-dependencies
> anthr76
> jonnobrow
> Another approach might be to have a single component chart which we can parameterize and include as a dependency multiple times with dependency aliasing: https://helm.sh/docs/topics/charts/#alias-field-in-dependencies
> This is exactly what I was thinking, and made what I think should be a completed implementation of the clientapi
> jonnobrow
> Okay great 👍 I'll take a look soon, there are some other bits I need to update/fix with the monolith chart and some refactoring that might help us in implementing polylith so I will try to do that over the next few days and keep you both updated.
> 
> Also, would it be possible to create an issue to track the work we are doing towards polylith and do any planning there?
> 
> anthr76
> Sure! I'll get one opened, and try to get these subcharts completed tonight. It would be great if we can get a release pushed to dendrite to support NATs so we can update the config file 
>

### PR DESCRIPTION
**Pull request by Jonnobrow**
**Description of the change**

Refactored values so each component has a key at the root rather than
nested within the dendrite.components section. This makes the
implementation and maintenance of polylith mode easier.

Split out volume template definitions into separate file.

Fixed NAT subchart indentation.

Added MSC's config and updated config version.

**Benefits**

- Both monolith and polylith deployments are supported.
- NATS and config have been updated to work correctly

**Possible drawbacks**

- Complete values redesign since v2.0.0 which will require major rework for config 

**Applicable issues**

- closes #1367 

**Additional information**

**Checklist** 
- [x] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Chart `artifacthub.io/changes` changelog annotation has been updated in `Chart.yaml`. See [Artifact Hub documentation](https://artifacthub.io/docs/topics/annotations/helm/#supported-annotations) for more info.
- [x] Variables have been documented in the `values.yaml` file.

### CODE REVIEW

**Comment by Jonnobrow** [comment]
Out of curiosity, would it be best to change the ci values to enable postgresql, nats and polylith mode so that the ci is testing the most complex permutation of this deployment? Or is there some way we can try multiple permutations, for example one with monolotih and one with polylith?

**Comment by bjw-s** [comment]
> Out of curiosity, would it be best to change the ci values to enable postgresql, nats and polylith mode so that the ci is testing the most complex permutation of this deployment? Or is there some way we can try multiple permutations, for example one with monolotih and one with polylith?

Given the (relative) complexity of the chart, I think that's a good idea! What you could do, is create a folder/file called `ci/ct-values.yaml`, which will get used by the CI flow. That will be the "main" values file that it will test with. You can add additional `*-values.yaml` files in that `ci` folder which will be run additionally. If you do a quick search through the repo you should be able to find one or two instances where we do something like this.

**Comment by Jonnobrow** [comment]
I am relying on a feature of Helm added by https://github.com/helm/helm/pull/9957 and merged in [v3.7.0](https://github.com/helm/helm/releases/tag/v3.7.0) which gives me the ability to access scope of subcharts. The CI for this repo still runs v3.6.3 it seems, am I able to update this or is there a reason its a few versions behind?

**Comment by bjw-s** [comment]
That is a pretty cool feature! TIL :)

There is no explicit reason we are still on that version. I will try to bump it tonight (the CI explicitly runs the CI definition that is in the `master` branch)

**Comment by bjw-s** [comment]
I have just bumped the dependencies

**Review by onedr0p — APPROVED** [review]

**Pull request merged**
