### PR TITLE
[unifi] Move traefik serversscheme annotations to service

### PR DESCRIPTION
**Pull request by alexwaibel**
**Description of the change**

Moves the Traefik `serversscheme` annotations from the ingresses to the service.

**Benefits**

Makes the Unifi controller web portal available.

**Possible drawbacks**

None that I'm aware of.

**Applicable issues**

- N/A

**Additional information**

Tested locally, confirmed that controller UI was not available prior to the change and is available afterwards.

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [x] Variables are documented in the README.md (this can be done with using our helm-docs wrapper `./hack/gen-helm-docs.sh stable <chart>`)

### CODE REVIEW

**Comment by bjw-s** [comment]
Change looks good :) As indicated by the bot, could you also update the chart documentation? Thanks a lot!! 🥇

**Comment by alexwaibel** [comment]
Might be worth adding those merge criteria from the bot posts to `CONTRIBUTING.md` as well

**Comment by bjw-s** [comment]
There are currently some issues with the domain name that is hosting our library charts. Will re-run the CI when those are resolved.

**Comment by alexwaibel** [comment]
> There are currently some issues with the domain name that is hosting our library charts. Will re-run the CI when those are resolved.

CI seems to all be passing now.

**Review by bjw-s — APPROVED** [review]

**Comment by bjw-s** [comment]
I just merged it. Thanks so much for the PR!

**Comment by bjw-s** [comment]
@all-contributors Please add @alexwaibel for code

**Pull request merged**
