### PR TITLE
[doods] new chart

### PR DESCRIPTION
**Pull request by runningman84**
#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[radarr]`)

### CODE REVIEW

**Comment by runningman84** [comment]
@billimek this chart needs an edge you therefore it would not work in the cicd system

**Comment by onedr0p** [comment]
@runningman84 as with https://github.com/k8s-at-home/charts/pull/153 do you think you refactor this into a chart that uses the common library?

I just pushed a change to zwave2mqtt which shows how the lib can be used with attaching a device.

https://github.com/k8s-at-home/charts/tree/master/charts/zwave2mqtt

**Comment by bjw-s** [comment]
Is the configuration in the ConfigMap reusable for everyone? Or does it need setup/user-specific content? Because in that case I think the file contents may be better off in a value in the `values.yaml`

**Comment by Ornias1993** [comment]
@runningman84 Instead of just rebasing, you also need to process the feedback from maintainers in the comments section... just to be sure ;-)

**Comment by bjw-s** [comment]
I've marked this PR as stale, since there hasn't been any activity for quite some time

**Comment by bjw-s** [comment]
Closing this one, since there hasn't been any activity for quite some time

**Pull request closed without merging**
