### PR TITLE
[dashmachine] remove DashMachine

### LINKED ISSUE #545: [dashmachine] Remove dashmachine or change to fork
Considering the steady increase of issues, a huge backlog of PR's without any activity and no commits for months: 
This project is clear vaporware/abandonware.
The consequences are potential security risks.

There are also great viable alternatives to this, like Heimdall or Organizr.

Taking into account this is already a VERY niche application: Either the used container needs to be changed to an active fork, or the application needs to be removed.

### PR DESCRIPTION
**Pull request by Ornias1993**
**Description of the change**

Dashmachine has been abandonware for quite a while now, the issues and PR's are piling up and the maintainer is unactive 
This creates significant security risks.

It's also quite a niche chart, with good alternative readily available

**Benefits**

- Not hosting potential security hazards

**Possible drawbacks**

- People can't collaborate on the chart anymore (although they first need to start collaborating on the actual software imho)

**Applicable issues**

- fixes #545

**Additional information**

**Checklist** 
- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [ ] Chart is using our [common](https://github.com/k8s-at-home/charts/tree/master/charts/common) library as a dependency.
- [ ] (optional) Variables are documented in the README.md

### CODE REVIEW

**Comment by bjw-s** [comment]
Normally it's considered best practice to deprecate the chart before deleting the files. See https://helm.sh/docs/topics/charts/#deprecating-charts.

I suggest keeping this PR open until a deprecated chart version has been merged.

**Comment by Ornias1993** [comment]
@bjw-s good point.
done see: #549

**Comment by bjw-s** [comment]
I've merged #549, but of course that now introduces a merge conflict for this PR 😓

**Comment by Ornias1993** [comment]
@bjw-s No problem, fixed!

**Review by bjw-s — CHANGES_REQUESTED** [review]
There's still a Chart.yaml left over, you'll need to remove that as well. Probably caused by the merge conflict earlier.

**Comment by Ornias1993** [comment]
Shoot.

**Review by bjw-s — APPROVED** [review]

**Pull request merged**
