### PR TITLE
[unifi] Rename port names for better traefik integration

### PR DESCRIPTION
**Pull request by cbergmann**
**Description of the change**

I changed the names of the ports for the captive portal from the format captive-http(s) to the format http(s)-captive.

**Benefits**

Traefik automatically talks to backends via https when the port name starts with https. [1]
Otherwise you have to add the annotation traefik.ingress.kubernetes.io/service.serversscheme: https to the service.

[1] https://doc.traefik.io/traefik/routing/providers/kubernetes-ingress/#communication-between-traefik-and-pods

**Possible drawbacks**

Some people might have configured external loadbalancers on the old name and therefore might experience problems when upgrading to a version with this change.

**Applicable issues**

none

**Additional information**

I don't know if this would bump the Chart version to 2.0.0 ?

**Checklist** 
- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x ] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [ ] (optional) Chart is using our [common](https://github.com/k8s-at-home/charts/tree/master/charts/common) library as a dependency.
- [ ] (optional) Variables are documented in the README.md

### CODE REVIEW

**Comment by onedr0p** [comment]
see as this could be considered a breaking change, please bump the major chart version in `Chart.yaml`

**Comment by onedr0p** [comment]
@cbergmann sorry one more change, you might have to rebase on-top of master.

**Comment by onedr0p** [comment]
thanks!

**Review by onedr0p — APPROVED** [review]

**Comment by cbergmann** [comment]
no problem. Glad I could help.

**Comment by onedr0p** [comment]
@all-contributors add @cbergmann for code

**Pull request merged**
