### PR TITLE
[autoscan] Inital Commit

### PR DESCRIPTION
**Pull request by dcplaya**
Autoscan replaces the default Plex and Emby behaviour for picking up 
file changes on the file system. Autoscan integrates with Sonarr, Radarr 
and Lidarr (with Google Drive coming soon!) to fetch changes in near 
real-time without relying on the file system.

#### Special notes for your reviewer:
Utilizes media-common since it shares the same mounts as the *arr services and just needs a config volume. 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[radarr]`)

### CODE REVIEW

**Comment by dcplaya** [comment]
Is this saying I need to bump the `media-common` chart version? All I added was an update to the `README`, didn't think that warranted a version bump

```
------------------------------------------------------------------------------------------------------------------------
 ✔︎ autoscan => (version: "1.0.0", path: "charts/autoscan")
 ✖︎ media-common => (version: "1.0.1", path: "charts/media-common") > Chart version not ok. Needs a version bump!
------------------------------------------------------------------------------------------------------------------------
Error: Error linting charts: Error processing charts
Error linting charts: Error processing charts
```

**Comment by carpenike** [comment]
yeah that likely means you need to bump both regardless of the change. @DirtyCajunRice

**Comment by dcplaya** [comment]
Do we want to keep bumping the `media-common` version each time? Chart definitely works, I have it running via my forked repo. I'll bump it if that's the course we want to take.

**Comment by carpenike** [comment]
@DirtyCajunRice -- any thoughts on an approach for these types of updates?

> Do we want to keep bumping the `media-common` version each time? Chart definitely works, I have it running via my forked repo. I'll bump it if that's the course we want to take.

**Comment by DirtyCajunRice** [comment]
> @DirtyCajunRice -- any thoughts on an approach for these types of updates?
> 
> 
> 
> > Do we want to keep bumping the `media-common` version each time? Chart definitely works, I have it running via my forked repo. I'll bump it if that's the course we want to take.
> 
> 
> 
> 

So if we are going by helm community standards - yes. A readme update is "technically" a change to the chart. The readme would not be reflected in installs or in repo aggregators like artifacthub without a bump.

Now the more human answer is probably "make a judgement call based on the value of the readme update... if it is enough to warrant the change it is probably worth bumping so people can see it"

finally: i think we should remove references to parent charts in the readme. you can see linked charts in artifacthub so doing this just causes cyclical updates.

**Comment by onedr0p** [comment]
@dcplaya any update here, should be close this?

**Comment by dcplaya** [comment]
I say close it. Devs are still working on the actual code and I have had a few times where the charts broke because something was modified on the backend (file locations, commands, ect). Just not ready for primetime.

**Comment by onedr0p** [comment]
Ok sounds good :)

**Pull request closed without merging**
