### PR TITLE
[wireguard] add standalone chart

### PR DESCRIPTION
**Pull request by jr0dd**
Figured I would finally send this over since I've been using this chart for awhile now in my personal repo. The probes might need some tweaking so open to suggestions if that is the case.

**Checklist** 
- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [X] Variables are documented in the README.md (this can be done with using our helm-docs wrapper `./hack/gen-helm-docs.sh stable <chart>`)

### CODE REVIEW

**Comment by jr0dd** [comment]
The install tests are failing because of the missing wg0.conf which is expected behavior with your container

**Comment by jr0dd** [comment]
updating the readme to reflect the requirement of wg0.conf to present

**Comment by onedr0p** [comment]
@jr0dd I think you need to add this chart to the ignore list here
https://github.com/k8s-at-home/charts/blob/master/.github/ct-install.yaml

**Comment by jr0dd** [comment]
@onedr0p done

**Comment by onedr0p** [comment]
Seems good to me, thanks!

**Review by onedr0p — APPROVED** [review]

**Pull request merged**
