### PR TITLE
[home-assistant] Fix env for appdaemon

### PR DESCRIPTION
**Pull request by lexfrei**
#### Special notes for your reviewer:

Looks like there was a copy-paste error and vscode extra vars was passed to appdaemon. Also:

- More flexible env configuration
- Now we can use secrets for token 

This change replaces `extraEnv` with `env` and `envFrom` and changes syntax. This doesn't look braking just coz it never worked before, but it's not consistent with else containers in this deployment. I can't imagine how should I change this to be consistent and get the same flexibility. If breaking changes is fine, I can replace all else envs with this syntax.

#### Checklist

- [x] Bump chart version
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[radarr]`)

#### Related:
#10

### CODE REVIEW

**Comment by lexfrei** [comment]
Also, I think we should remove all preset envs and just mention them in a comment before env block. But it's breaking changes so not done yet

**Review by onedr0p — APPROVED** [review]

**Comment by onedr0p** [comment]
Thanks for the PR @lexfrei 👍

**Comment by lexfrei** [comment]
@onedr0p should i rewrite env templateing for whole deployment?
They will be more useful, but the change will break backward compatibility.

**Comment by onedr0p** [comment]
Sure! Let's see what you're thinking of in the PR just make sure to bump major version and write in the changelog

**Pull request merged**
