### PR TITLE
[adguard-home] fix conf mount path

### PR DESCRIPTION
**Pull request by n0rad**
The init container do not share the conf directory adguard container. So Moving the conf doing nothing.

This PR make the conf directory shared between the 2 containers and so fix as code configuration

### CODE REVIEW

**Comment by bjw-s** [comment]
Good catch on this one! Your modification to the initContainer should work, but I don't think the additionalVolumes changes will work. Would it be OK if I submit some changes to your PR to see if I can fix it / make the initContainer depend on the existing persistence settings?

**Comment by n0rad** [comment]
Sure ! fill free to commit, I was not sure on how to fix the conflict between the user defined volume and the empty dir volume needed to do the copy.

**Comment by onedr0p** [comment]
@n0rad I think this might be a good workaround

https://github.com/k8s-at-home/charts/pull/785

**Comment by onedr0p** [comment]
@all-contributors add @n0rad for code

**Pull request closed without merging**
