### PR TITLE
[mopidy] Add new chart

### PR DESCRIPTION
**Pull request by lanquarden**
Signed-off-by: lanquarden <lanquarden@gmail.com>

**Description of the change**

Adding mopidy chart

**Benefits**

Easily run a mopidy instance in your cluster

**Possible drawbacks**

It's a official container from the Iris project (web frontend), but it is not following semver, they just update the latest tag with every release of the web frontend. I think that I'll probably end up creating a headless container and a one with the frontend where the different plugins to install are configurable.

**Applicable issues**

- fixes #

**Additional information**

The same as for the snapcast chart, bare bones helm that was tested manually with a helm install. s I learn how to successfully deploy this together with a snapcast chart I'll try to find a way to poor that back into the documentation/values.yaml

**Checklist** 
- [X] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Chart `artifacthub.io/changes` changelog annotation has been updated in `Chart.yaml`. See [Artifact Hub documentation](https://artifacthub.io/docs/topics/annotations/helm/#supported-annotations) for more info.
- [X] Variables have been documented in the `values.yaml` file.

### CODE REVIEW

**Comment by Truxnell** [comment]
Hi @lanquarden 
Thanks for the PR!  Looks like it is failing install with default config, can you have a look?
Ideally our charts will pass CI for a basic install without erroring.

**Comment by lanquarden** [comment]
I hope latest commit fixes the although I can't trigger the CI

**Review by Truxnell — CHANGES_REQUESTED** [review]
Just a few minor linting changes

**Comment by lanquarden** [comment]
Updated indent for yaml lists, did same update in the template

**Comment by Truxnell** [comment]
@lanquarden Awesome, ta

I forgot in the review - you can (like im just writing in the snapcast chart) use `appVersion: latest` in the `Chart.yaml` and then leave `tag:` as blank in the `values.yaml`
The vaules.yaml inherits from the Chart.yaml appversion (thats what `  # @default -- chart.appVersion
` does).  This saves you having to update both tags if you chose to keep images bumped in the helm - you can just bump in chart only.

**Comment by lanquarden** [comment]
I think I got it all, `latest` in Chart, no tag in `values.yaml` in both PRs

**Review by Truxnell — APPROVED** [review]

**Comment by Truxnell** [comment]
Thanks for the PR!

@all-contributers, can you please add @lanquarden for code

**Comment by Truxnell** [comment]
Thanks for the PR!

@all-contributors, can you please add @lanquarden for code

**Comment by Truxnell** [comment]
Thanks for the PR!

@all-contributors can you please add @lanquarden for code

**Pull request merged**
