### PR TITLE
[reverse-proxy] Fix ingressclass generation

### PR DESCRIPTION
**Pull request by ishioni**
**Description of the change**
The logic behind setting the ingressclass had a typo - it watched for .ingress.ingressclass but took it's value from .ingressclass

**Benefits**
Ingressclasses are set now

**Possible drawbacks**
None

**Applicable issues**

- fixes #

**Additional information**

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [x] Variables are documented in the README.md (this can be done with using our helm-docs wrapper `./hack/gen-helm-docs.sh stable <chart>`)

### CODE REVIEW

**Review by angelnu — APPROVED** [review]
Thanks for the fix - ILGTM

**Review by bjw-s — CHANGES_REQUESTED** [review]
As indicated by @angelnu , the change looks good, only missing the docs.

**Comment by ishioni** [comment]
What exactly in the docs do you need? I was wondering about that since there was nothing about 2.1..

**Comment by onedr0p** [comment]
@ishioni please see the comment left above https://github.com/k8s-at-home/charts/pull/1327#issuecomment-1000982813

**Review by bjw-s — APPROVED** [review]

**Comment by angelnu** [comment]
@ishioni - 2.1 was an automated update after a change in the base library. The PR generator does not edit comments.

@bjw-s @onedr0p - now that all charts follow the changelog template we could also add entries when we update the base chart, right? So "just" work?

**Comment by bjw-s** [comment]
> @bjw-s @onedr0p - now that all charts follow the changelog template we could also add entries when we update the base chart, right? So "just" work?

The problem is that Renovate has no idea about our changelogs, making it a lot of manual effort. For now we've only been doing it for major library versions

**Pull request merged**
