### PR TITLE
[photoprism] Update photoprism image

### PR DESCRIPTION
**Pull request by titilambert**
**Description of the change**

**Benefits**

**Possible drawbacks**

**Applicable issues**

- fixes #

**Additional information**

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [x] Variables are documented in the README.md (this can be done with using our helm-docs wrapper `./hack/gen-helm-docs.sh stable <chart>`)

### CODE REVIEW

**Comment by bjw-s** [comment]
Thanks for pushing this update! Change looks good 👍 

I did notice you did not run the `./hack/gen-helm-docs.sh stable <chart>` to update the chart's README.md file. If you can do this I will go ahead and approve/merge this PR.

**Review by bjw-s — CHANGES_REQUESTED** [review]
Thanks for pushing this update! Change looks good 👍 

I did notice you did not run the `./hack/gen-helm-docs.sh stable <chart>` to update the chart's README.md file. If you can do this I will go ahead and approve/merge this PR.

**Comment by titilambert** [comment]
@bjw-s Thanks for your comment, It's now fixed

**Review by onedr0p — APPROVED** [review]

**Comment by onedr0p** [comment]
@all-contributors please add @titilambert for code

**Pull request merged**
