### PR TITLE
add ISSUE_TEMPLATE

### PR DESCRIPTION
**Pull request by onedr0p**
#### Special notes for your reviewer:

Create issue templates for the charts repo

### CODE REVIEW

**Comment by carpenike** [comment]
Is it worthwhile to pre-embed the title with the request type?

**Comment by bjw-s** [comment]
> Is it worthwhile to pre-embed the title with the request type?

Isn't that also covered by the labels? Or do you think it would have benefit to add "[<chart-name>] " as a prefix to the bug/enhancement titles?

**Comment by carpenike** [comment]
Labels should be fine as well as they show up in the default table view.

**Comment by onedr0p** [comment]
We can always update these later on with improvement, this is a good base

LGTM :)

**Pull request merged**
