### PR TITLE
[unifi] enhance unifi to log to stdout

### PR DESCRIPTION
**Pull request by billimek**
**Description of the change**

Enhance the unifi helm chart to send server output to `stdout` in addition to the server.log, thanks to [this PR](https://github.com/jacobalberty/unifi-docker/pull/405).

**Benefits**

unifi will send server logs to stdout, making it easier to discover log messages from the unifi controller using your favorite kubernetes logging solution

**Possible drawbacks**

This will probably duplicate and possible deprecate the existing promtail logging shim added to the chart previously.  IMO sending the logs to stdout is a superior approach now that it is an option.

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [ ] Chart is using our [common](https://github.com/k8s-at-home/charts/tree/master/charts/common) library as a dependency.
- [ ] (optional) Variables are documented in the README.md

### CODE REVIEW

**Comment by billimek** [comment]
@michaelkoetter do you have any thoughts on this?  You originally added the promtail integration and I would like to see what you think of this approach.

**Comment by ishioni** [comment]
@billimek One thing you should know about this - it will pipe the controller log, but NOT the mongo log. No way to achieve that unless you're using a separate mongo instance i'm afraid :(

**Comment by billimek** [comment]
> @billimek One thing you should know about this - it will pipe the controller log, but NOT the mongo log. No way to achieve that unless you're using a separate mongo instance i'm afraid :(


Thanks!  I noticed the lack of mongo tailing as well but still saw this as a net gain because right now the default stdout logging is pretty useless. 

Can you think of a reason not to have this set and enabled by default?

**Comment by ishioni** [comment]
Just the mongo issue. Except for that, it should be The Better Way[TM]

**Review by bjw-s — APPROVED** [review]

**Comment by bjw-s** [comment]
LGTM except for the conflicts ;)

**Pull request merged**
