### PR TITLE
[focalboard] add chart for focalboard

### PR DESCRIPTION
**Pull request by FlipEnergy**
Signed-off-by: Dennis Zhang <dennis.zhang.nrg@gmail.com>

**Description of the change**
A new incubator chart for Focalboard

**Benefits**
A new incubator chart for Focalboard

**Possible drawbacks**

**Applicable issues**

- fixes #

**Additional information**

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [x] Variables are documented in the README.md (this can be done with using our helm-docs wrapper `./hack/gen-helm-docs.sh stable <chart>`)

### CODE REVIEW

**Comment by FlipEnergy** [comment]
Question, I assume automation will still put this chart in the helm charts repo despite being an incubator chart?

**Comment by bjw-s** [comment]
> Question, I assume automation will still put this chart in the helm charts repo despite being an incubator chart?

It definitely should, but it being the first incubator chart we're going to find out for sure 😉

**Comment by onedr0p** [comment]
Incubator should be used for charts that need to be tested, i.e. anything that might not be straight forward. You can put this in stable

**Comment by FlipEnergy** [comment]
> 
> 
> Incubator should be used for charts that need to be tested, i.e. anything that might not be straight forward. You can put this in stable

sounds good to me. It should work fine as is. To stable!

**Review by bjw-s — APPROVED** [review]
Looks good 👍🏻

**Pull request merged**
