### PR TITLE
[blocky] refactor config and bump version

### PR DESCRIPTION
**Pull request by onedr0p**
**Description of the change**

- Update version to v0.12
- Sync config.yaml from https://github.com/0xERR0R/blocky/blob/development/docs/config.yml

**Benefits**

**Possible drawbacks**

**Applicable issues**

- fixes #

**Additional information**

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [ ] Chart is using our [common](https://github.com/k8s-at-home/charts/tree/master/charts/common) library as a dependency.
- [x] (optional) Variables are documented in the README.md

### CODE REVIEW

**Review by bjw-s — COMMENTED** [review]
I feel these changes to the values.yaml could maybe warrant a breaking change...

If somebody hasn't set up values that used to be commented out and are now provided with a default, some very unexpected behavior might occur. For example `clientLookup.upstream` or enabling a whitelist by default

**Comment by onedr0p** [comment]
Doesn't the config get overridden when provided by the user, or does this gets merged by helm as well?

**Comment by bjw-s** [comment]
I believe they all get merged together with the values provided by the user.

So if before I didn't have a whitelist set, and then deploy this chart, all of a sudden I get a whitelist "for free". Same with `config.clientLookup`. If I didn't have it before and don't override it, then all of a sudden I would now get a `config.clientLookup.upstream` value of `udp:192.168.178.1` which could break things.

**Comment by onedr0p** [comment]
That doesn't seem ideal, I feel like this config shouldn't be merged.

I guess the only way todo this would be to make the configmap a string... e.g.

```yaml
config: |
  upstream:
    externalResolvers:
    - 1.1.1.1
    - 9.9.9.9
    conditional:
    ...
```

**Comment by bjw-s** [comment]
Yep, that could work (and may even be the best way to go). That way the config that is defined in user values.yaml is going to be exactly what is passed into the pod.

**Comment by onedr0p** [comment]
@billimek I know originally the chart was made that way, do you see any reason to keep it the way it is currently? Obviously this would be a breaking change.

**Comment by billimek** [comment]
> @billimek I know originally the chart was made that way, do you see any reason to keep it the way it is currently? Obviously this would be a breaking change.

I've been following this PR and think this proposed way makes more sense.  I can't see a good scenario where we would want some blocky config defaults merged with custom config settings.

**Comment by onedr0p** [comment]
Sounds like we have a plan, I'll update this pr to do that and label the version breaking

**Comment by onedr0p** [comment]
Going to go ahead and merge this, thanks for the support @bjw-s :D

**Comment by bjw-s** [comment]
👍🏻

**Pull request merged**
