### PR TITLE
[uptime-kuma] Fixed bug in uptime kuma values.yaml regarding persistence

### PR DESCRIPTION
**Pull request by maxemann96**
**Description of the change**
Changed the key `persistence.data` to `persistence.config` in `values.yaml`

**Benefits**
Users without any prior knowledge of k8s@home charts are now easier be able to deploy this chart with persistence

**Possible drawbacks**
no

**Applicable issues**
no one

- fixes #

**Additional information**

**Checklist** 
- [x] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Chart `artifacthub.io/changes` changelog annotation has been updated in `Chart.yaml`. See [Artifact Hub documentation](https://artifacthub.io/docs/topics/annotations/helm/#supported-annotations) for more info.
- [ ] Variables have been documented in the `values.yaml` file. (Not needed, no change of actual variable)

### CODE REVIEW

**Comment by bjw-s** [comment]
I'm not entirely sure what the exact bug is here that you are trying to fix.

It's only the name of the volume that gets set within the Pod, and the mountPoint seems to indicate that it contains application data?

**Comment by maxemann96** [comment]
As far as I understand the [persistence configuration](https://docs.k8s-at-home.com/our-helm-charts/common-library-storage/) of the common library used as dependency in this chart, it is needed to configurate the persistence under the key `persistence.config` and not `persistence.data` as stated in the `values.yaml` before.

**Comment by maxemann96** [comment]
Got now how it's working. The initial error lead me to this change was that "accessMode is not defined for pvc ..." and I was searching for a solution why it not works. I found no documentation, that `persistence.x` is just a key defining the name of the pvc and was irritated, because the common chart template only documents the `config` key with some default values and I thought that there are then default values for all other keys than `config` or the key is wrong. 

Thanks for your patience

**Comment by bjw-s** [comment]
No worries! Glad you got your initial issue sorted and thank you for wanting to submit a fix!

**Pull request closed without merging**
