### PR TITLE
[powerdns] flip default to postgres, fix postgres dependent chart

### PR DESCRIPTION
**Pull request by carpenike**
#### Special notes for your reviewer:
Found a bunch of weird stuff that I overlooked...

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[radarr]`)

### CODE REVIEW

**Comment by carpenike** [comment]
Dependent docker image doesn’t support Postgres. Holding off on this merge till https://github.com/psi-4ward/docker-powerdns/pull/23 is complete.

**Comment by onedr0p** [comment]
Looks like that PR is nearly 2 years old, should we close this issue and remove postgres from the chart?

**Comment by carpenike** [comment]
@onedr0p -- going to adjust the chart to use the image created by @naps in #94

**Comment by carpenike** [comment]
Closes #94

**Comment by onedr0p** [comment]
This PR should be rebased. after that, @carpenike is it ready for review?

**Comment by carpenike** [comment]
Not yet... apparently i'm not setting the postgres password properly.

**Comment by bjw-s** [comment]
> Not yet... apparently i'm not setting the postgres password properly.

I see in the action logs that the powerDNS pod is failing due to livenessProbe failures. The postgresql pod takes some time to boot up, maybe it hasn't properly connected to the database in time (not that I see it trying to do that in the logs though)?

**Comment by carpenike** [comment]
@bjw-s -- I'm wondering if it's due to the init process from PowerDNS not running / creating the zone...

Trying to back-port current config into 5c64c19.

**Comment by carpenike** [comment]
> @bjw-s -- I'm wondering if it's due to the init process from PowerDNS not running / creating the zone...
> 
> Trying to back-port current config into [5c64c19](https://github.com/k8s-at-home/charts/commit/5c64c197bd2d2f22385a9e21ec265b3d0e8f6d66).

Likely due to the fact that the new docker image doesn't deploy the webserver so the probes were failing. Flipping to tcp port

**Comment by carpenike** [comment]
This should get a working deployment of PowerDNS without the Web API. Will take a crack at that next ones @naps confirms core functionality.

**Review by onedr0p — APPROVED** [review]
👍

**Pull request merged**
