### PR TITLE
[recipes] update tandoor version and adjust default upload size

### PR DESCRIPTION
**Pull request by xMAC94x**
**Description of the change**

Tandoor version hasnt updated for half a year. updating its and nginx sidecar version.
Also the repo sugest to increase client max body size to 128M: https://github.com/TandoorRecipes/recipes/blob/develop/nginx/conf.d/Recipes.conf

**Benefits**

More up to date by default and more recent security patches

**Possible drawbacks**

No known

**Applicable issues**

No known

**Additional information**

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [X] Variables are documented in the README.md (this can be done with using our helm-docs wrapper `./hack/gen-helm-docs.sh stable <chart>`)

### CODE REVIEW

**Comment by bjw-s** [comment]
Thanks very much for updating the image/chart! I noticed that you updated the `README.md` file by hand, but that is not required. We generate our README.md file automatically based on the available chart (meta)data:

https://docs.k8s-at-home.com/our-helm-charts/development/creating-a-new-chart/#chart-metadata

**Comment by xMAC94x** [comment]
Hi @bjw-s  i have a few questions/issues:
- I tried to update the README.md and it returned:
```bash
$ ./hack/gen-helm-docs.sh stable recipes                                                                                                                                                                                                                 Copying templates to /home/marcel/tmp/k8s_at_home_charts/charts/stable/recipes
INFO[2022-01-30T17:23:15+01:00] Found Chart directories [.]
INFO[2022-01-30T17:23:15+01:00] Generating README Documentation for chart /home/marcel/tmp/k8s_at_home_charts/charts/stable/recipes
WARN[2022-01-30T17:23:15+01:00] Error generating gotemplates for chart /home/marcel/tmp/k8s_at_home_charts/charts/stable/recipes: template: /home/marcel/tmp/k8s_at_home_charts/charts/stable/recipes:120: function "fromYaml" not defined
```

The Bot suggest me to follow semver, i am not sure what the API i semver is against ? Anyone can upgrade without needing to update their values.yaml file, but the app had a major version in between, so does it mean this also needs to be a major version upgrade?

The Bot said that i should update https://artifacthub.io/packages/helm/k8s-at-home/recipes, i have never used that webside, but i doubt i have the permissions o create a new version there containing:
```
#### Changed

* Upgraded `tandoor` to version `1.0.5.2` and `nginx` sidecar `1.21.6`.
```
```

**Comment by bjw-s** [comment]
> * I tried to update the README.md and it returned:
> ```
> WARN[2022-01-30T17:23:15+01:00] Error generating gotemplates for chart /home/marcel/tmp/k8s_at_home_charts/charts/stable/recipes: template: /home/marcel/tmp/k8s_at_home_charts/charts/stable/recipes:120: function "fromYaml" not defined
> ```

As stated in the docs I linked to, we use a custom version of helm-docs. That should solve the error above.

> The Bot suggest me to follow semver, i am not sure what the API i semver is against ? Anyone can upgrade without needing to update their values.yaml file, but the app had a major version in between, so does it mean this also needs to be a major version upgrade?

That is a very good question, but not one I can answer easily. Normally we determine the Helm values to be the API, but if we know that a tag update will (most likely) break the configuration that a user is running we bump the major version and include a remark about this in the changelog.

> The Bot said that i should update https://artifacthub.io/packages/helm/k8s-at-home/recipes, i have never used that webside, but i doubt i have the permissions o create a new version there containing:

You don't need to update anything on the ArtifactHub website. It is enough to update the `chart.yaml` file with an `annotations` key. You can check out [this](https://github.com/k8s-at-home/charts/blob/master/charts/stable/deconz/Chart.yaml#L24L31) for an example.

Hopefully that helps answer your questions?

**Review by bjw-s — APPROVED** [review]
LGTM :)

**Pull request merged**
