### PR TITLE
[monica] Remove default empty env variables - along the same lines as #1455

### PR DESCRIPTION
**Pull request by halkeye**
**Description of the change**

Remove default env variables for monica

**Benefits**

Allows env variables to be populated by secrets

**Possible drawbacks**

Anyone depending on the default values will have things break

**Applicable issues**

- related to #1455 (wikijs)

**Additional information**

**Checklist** 
- [X] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Chart `artifacthub.io/changes` changelog annotation has been updated in `Chart.yaml`. See [Artifact Hub documentation](https://artifacthub.io/docs/topics/annotations/helm/#supported-annotations) for more info.
- [X] Variables have been documented in the `values.yaml` file.

### CODE REVIEW

**Review by onedr0p — APPROVED** [review]

**Comment by samip5** [comment]
Why was this not an major version? That's a breaking change tho.

**Comment by onedr0p** [comment]
How so? There were no default values changed, just envars commented out.

**Comment by halkeye** [comment]
If i were to guess, APP_KEY might have accepted a blank string in the past? Its supposed to be a random hash, but maybe empty string was allowed? The "defaults" seem pretty bad to used

**Comment by samip5** [comment]
> How so? There were no default values changed, just envars commented out.

If one used the env variables that were set in the helm chart, that's an breaking change to have them removed from the defaults even if such configuration is not secure.

**Comment by halkeye** [comment]
> If one used the env variables that were set in the helm chart, that's an breaking change to have them removed from the defaults even if such configuration is not secure.

What defaults were you using that don't work now? The defaults were empty, so the new values are non set, in most languages they are the same.

Or is this just hypothetical?

**Pull request merged**
