### PR TITLE
[deepstack] add deepstack-ui

### PR DESCRIPTION
**Pull request by angelnu**
**Description of the change**

add [deepstack-ui](https://github.com/robmarkcole/deepstack-ui)

**Benefits**

UI to manage deepstack models

**Possible drawbacks**

**Applicable issues**

- related to #1273 

**Additional information**

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [x] Variables are documented in the README.md (this can be done with using our helm-docs wrapper `./hack/gen-helm-docs.sh stable <chart>`)

### CODE REVIEW

**Comment by angelnu** [comment]
@crutonjohn @onedr0p - I added the deepstack-ui to the chart - it makes easier to manage faces and models.

**Comment by crutonjohn** [comment]
very cool. full disclosure i haven't even had a chance to install this chart yet.

**Comment by angelnu** [comment]
I am running with it and attached to the home-assistant. 

Thanks a los for the chart

**Comment by onedr0p** [comment]
Would it be better to add this to the existing helm chart as a sidecar?

**Comment by onedr0p** [comment]
Derp, I haven't had my coffee yet. Please ignore me haha

**Review by onedr0p — APPROVED** [review]

**Pull request merged**
