### PR TITLE
transmission: move pulling of theme as a custom startup probe

### PR DESCRIPTION
**Pull request by jr0dd**
Due to limitations of network connectivity and initcontainers, I moved the pulling of flood theme to the startup probe instead. Tested working.

### CODE REVIEW

**Comment by jr0dd** [comment]
> I am going to play with this one day and see if I can get it installed using the initContainer and actaully test. While startupProbe works it's not how it should be used in k8s.

yeah it's definitely hacky. i don't like it, but could not figure out a way to get an initcontainer to get access to the internet.

**Comment by jr0dd** [comment]
A better solution would probably be just adding the tar file to the container image and then using the initcontainer to untar and move to /config

**Comment by onedr0p** [comment]
initContainers _should_ have network access. I am curious what the error logs on your end was?

**Comment by jr0dd** [comment]
> initContainers _should_ have network access. I am curious what the error logs on your end was?

The only output i get is curl unable to resolve github.com before the initcontainer crashes. I tried adding `--dns-servers 1.1.1.1` to the curl command which didn't resolve. I tried multiple images instead of the curl image and same issue.

**Comment by bjw-s** [comment]
I personally feel that startupProbes should not be "abused" for such behavior. A startupProbe is meant to determine if an application has started (hence the name). As @onedr0p states, initContainers _should_ normally have normal networking functionality.

Maybe we can add a test case for this to the `ci` folder so that we can verify if the initContainer works as intended?

**Comment by onedr0p** [comment]
> Maybe we can add a test case for this to the ci folder so that we can verify if the initContainer works as intended?

There is one in the ci values, unless I did something wrong it's been working.

**Comment by bjw-s** [comment]
> There is one in the ci values, unless I did something wrong it's been working.

I must admit I didn't check before mentioning it 😅

**Comment by jr0dd** [comment]
> I personally feel that startupProbes should not be "abused" for such behavior. A startupProbe is meant to determine if an application has started (hence the name). As @onedr0p states, initContainers _should_ normally have normal networking functionality.
> 
> Maybe we can add a test case for this to the `ci` folder so that we can verify if the initContainer works as intended?

Yeah I probably jumped the gun sending a pr for such a hacky thing lol. I'm a little baffled by any initcontainer image I have tried to get outside access. The kubernetes documentation clearly states that initcontainers can be used to pull a git repo. I stuck the curl command in an until loop and let it ran for 15min. Did not resolve. The issue could very well be somewhere obscure on my end. I'll close this pr.

**Pull request closed without merging**
