### PR TITLE
[mosquitto-exporter] Add a new helm chart for mosquitto prometheus exporter

### PR DESCRIPTION
**Pull request by nolte**
#### Special notes for your reviewer:

New Chart for Deploy a [Prometheus Exporter](https://github.com/sapcc/mosquitto-exporter) for mosquitto.

#### Checklist
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[radarr]`)

### CODE REVIEW

**Comment by billimek** [comment]
@nolte what do you think about integrating this into the existing [mosquitto chart](https://github.com/k8s-at-home/charts/tree/master/charts/mosquitto) itself instead of a standalone chart, enabled/disabled by a feature flag in the values.yaml?

Maybe instead of a standalone `Deployment`, the container could run as a sidecar?

**Comment by nolte** [comment]
@billimek i think the integration as optional sidecar and a PodMonitor its a good a good idea. I will test it, and create a new PR if it works.

**Comment by onedr0p** [comment]
I think this is great being a part of the mosquitto chart as well.

**Comment by onedr0p** [comment]
Closing in favor of

https://github.com/k8s-at-home/charts/pull/118

**Pull request closed without merging**
