### PR TITLE
[uptime-kuma] Add new chart

### PR DESCRIPTION
**Pull request by pysen**
**Description of the change**

I'm adding a simple [uptime-kuma](https://github.com/louislam/uptime-kuma) deployment as statping looks to have been abandoned by the developer. 

**Benefits**

It adds an alternative to statping!

**Possible drawbacks**
None

**Applicable issues**
None

**Additional information**

**Checklist** 
- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [X] Variables are documented in the README.md (this can be done with using our helm-docs wrapper `./hack/gen-helm-docs.sh stable <chart>`)

### CODE REVIEW

**Comment by onedr0p** [comment]
Good find on statping, looks like the successor is over at https://github.com/statping-ng/statping-ng

**Review by onedr0p — DISMISSED** [review]
Please move this into the stable directory

**Comment by pysen** [comment]
> Please move this into the stable directory

I've moved the chart in https://github.com/k8s-at-home/charts/pull/1288/commits/116eec7e733f9c50189e6ea172d2b247edc73636 to stable.

**Comment by pysen** [comment]
@onedr0p The commented out environment variable were the only lines I could find that fits the error message in the linting. Fixed in https://github.com/k8s-at-home/charts/pull/1288/commits/39bb342774191192927f55bbdecb9363d4aa906e

**Comment by onedr0p** [comment]
Almost there, I think you need to set the chart version to 1.0.0 and rerun the helm-docs

**Comment by pysen** [comment]
@onedr0p I've rebased my branch & included the corrected docs in the latest commit.

**Review by onedr0p — APPROVED** [review]

**Comment by onedr0p** [comment]
@all-contributors add @pysen for code

**Pull request merged**
