### PR TITLE
[onedrive] Add Chart

### PR DESCRIPTION
**Pull request by wrmilling**
**Description of the change**

Create a chart for the OneDrive linux client from [abraunegg](https://github.com/abraunegg/onedrive). 

**Benefits**

The ability to deploy OneDrive to a k8s cluster to sync files from Microsoft's OneDrive product. 

**Possible drawbacks**

N/A

**Applicable issues**

N/A

**Additional information**

**Checklist**
- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [X] Variables are documented in the README.md (this can be done with using our helm-docs wrapper `./hack/gen-helm-docs.sh stable <chart>`)

### CODE REVIEW

**Comment by wrmilling** [comment]
I have `latest` as the current tag in the values.yaml, its a testing docker image that I am maintaining. If it works as expected, I will upstream the changes and go to a specific version tag on the upstream docker image.

**Review by rwaltr — APPROVED** [review]
Looks solid to me

**Comment by onedr0p** [comment]
I am thinking the action will fail, does it work with default settings?

**Comment by wrmilling** [comment]
It looks like the container has an issue with the `entrypoint.sh` script. I will test it again locally and see if I can fix whatever is wrong. Permissions issue I am guessing.

**Review by onedr0p — APPROVED** [review]

**Pull request merged**
