### PR TITLE
[transmission] always use chart-defined config

### PR DESCRIPTION
**Pull request by ishioni**
**Description of the change**
The chart now always uses the chart-defined transmission config

**Benefits**
App config is now idempotent

**Possible drawbacks**

**Applicable issues**

- fixes #

**Additional information**

**Checklist** 
- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [X] (optional) Chart is using our [common](https://github.com/k8s-at-home/charts/tree/master/charts/common) library as a dependency.
- [X] (optional) Variables are documented in the README.md

### CODE REVIEW

**Review by Ornias1993 — CHANGES_REQUESTED** [review]
Serieusly, the values.yaml is always going to override my persistante config file, made by myself?!
Sorry, bad design.

**Comment by ishioni** [comment]
You can change it in values.yaml, hence the idempotence. I realise there are settings you can change in the UI, and they will be lost on container reboot, but unfortunately they are mixed in with more important network settings which need to be set on install. This is the lesser of 2 evils. The linuxserver image offsets this somewhat, but a vanilla transmission installation only listens on localhost, and there's a rootless vanilla transmission image in the works which is targeted for this chart

**Comment by onedr0p** [comment]
> Serieusly, the values.yaml is always going to override my persistante config file, made by myself?!
> 
> Sorry, bad design.

Disagreed. Transmission doesn't let you change these values at runtime. It makes absolute sense here.

**Comment by Ornias1993** [comment]
> The linuxserver image offsets this somewhat, but a vanilla transmission installation only listens on localhost, and there's a rootless vanilla transmission image in the works which is targeted for this chart

Okey, that does get increasingly problematic indeed.

**Review by onedr0p — APPROVED** [review]

**Comment by onedr0p** [comment]
Looks good to me, I'll wait for @bjw-s approval to merge 😅

**Comment by ishioni** [comment]
> Looks good to me, I'll wait for @bjw-s approval to merge 😅

I pinged him on discord, he'll take a look at it in the evening :)

**Review by bjw-s — APPROVED** [review]
LGTM as well 👍 🥳

**Pull request merged**
