### PR TITLE
[All] Update pre commit

### PR DESCRIPTION
**Pull request by Ornias1993**
**Description of the change**

This PR adds to more features to precommit:
- Removal of tabs
- Removing crlf (To prevent any future issues creeping up)

The second commit contains a full run of pre-commit

**Benefits**

It limits the amount of future issues and cleans up the repository a bit

**Possible drawbacks**
- Slightly longer pre-commit runtimes
- Lots of changed files in one PR

**Applicable issues**

- fixes #

**Additional information**

- Chart versions are increased for all charts that have non-readme changes to prevent any CI issues

**Checklist** 
- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [X] Variables are documented in the README.md (this can be done with using our helm-docs wrapper `./hack/gen-helm-docs.sh stable <chart>`)

### CODE REVIEW

**Comment by Ornias1993** [comment]
@bjw-s The linting is just the fact that the linter doesn't ignore based on Readme vs non-readme file for version checking.
However: I'm not going to manually increase the versions of 40 apps to please a linter.

**Comment by bjw-s** [comment]
I similarly won't be manually checking 166 changed files to see if something may have been missed that could have easily been caught by a linter / CI install job.

The alternative is that we only commit the pre-commit config changes and omit the cleanup run altogether.
We'll then run the pre-commit cleanup on those when we release the next version of the common library / chart. Additionally I'll see if I can add the pre-commit job to the CI as well, so that any errors are automatically caught in the future.

**Comment by Ornias1993** [comment]
@bjw-s Fine with me to cherry just the pre-commit changes :)

**Comment by bjw-s** [comment]
Incoming with https://github.com/k8s-at-home/charts/pull/845 :)

**Comment by Ornias1993** [comment]
I think this is depricated by the great work of @bjw-s by now :)

**Pull request closed without merging**
