### PR TITLE
[common] 2.0.0

### PR DESCRIPTION
**Pull request by onedr0p**
#### Special notes for your reviewer:

Renovate changes
Github workflow changes

Closes https://github.com/k8s-at-home/charts/issues/314
Closes https://github.com/k8s-at-home/charts/issues/312
Closes https://github.com/k8s-at-home/charts/issues/311

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[radarr]`)

### CODE REVIEW

**Comment by onedr0p** [comment]
Added `fullnameOverride` and `nameOverride` in `values.json`

**Comment by onedr0p** [comment]
Added `envFrom`

**Comment by bjw-s** [comment]
Added support for custom probe definitions

**Comment by bjw-s** [comment]
Modified the probe logic to loop over the available probes.
Also bumped the chart with a major version due to potential breaking changes to the probe configuration.

**Pull request merged**
