### PR TITLE
[alertmanager-discord] Add new chart

### PR DESCRIPTION
**Pull request by rogerrum**
**Description of the change**

Add the new chart for simple golang application, which listens for Prometheus Alertmanager's notifications and pushes them to Discord channel.

**Benefits**

The current Alertmanager config does not support discord, we can use the Slack-Compatible discord webhook but there are payload size limitations on the Slack-Compatible webhook and if multiple alerts firing then the webhook errors out. This application is custom alertmanager webhook and accepts the notification and sends to discord webhook.

Example config
https://github.com/rogerrum/k8s-gitops/blob/46fbfb0b047cbf4bb6bcb573b66c18232755ce63/main/monitoring/kube-prometheus-stack/kube-prometheus-stack-secret-alertmanager.txt#L56

**Possible drawbacks**

Needs extra deployment for the webhook vs using the slack compatible webhook.

**Applicable issues**

- fixes #

**Additional information**

**Checklist**
- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [X] Variables are documented in the README.md (this can be done with using our helm-docs wrapper `./hack/gen-helm-docs.sh stable <chart>`)

### CODE REVIEW

**Comment by onedr0p** [comment]
Re-opening to trigger the workflows again

**Comment by onedr0p** [comment]
@rogerrum You can either update this chart to be excluded from tests, or update your application to not exit when you don't supply all the right config

```
==> Logs of container alertmanager-discord-yu4qzgmwra-856f6c8888-fgrzs
------------------------------------------------------------------------------------------------------------------------
2021/12/29 19:19:36 Environment variable 'DISCORD_WEBHOOK' or CLI parameter 'webhook.url' not found.
```

**Comment by rogerrum** [comment]
@onedr0p Thanks for the info. I have excluded the chart from test. The webhook url is required parameter so will keep the app as failing if the url is not provided.

**Review by onedr0p — APPROVED** [review]

**Comment by onedr0p** [comment]
@all-contributors add @rogerrum for code

**Pull request merged**
